### ISSUE TITLE
Improved navigation and visibility in the Settings card

### ISSUE THREAD

**Issue by sol-znn** [hypercore-one/syrius#14]
**Is your feature request related to a problem? Please describe.**
I want to re-order the Settings card, relocating some widgets to the Info tab.
The goal is to remove clutter from Settings, improve navigation and visibility.
Node Management is clunky to access and should be made more prominent.

**Describe the solution you'd like**
Settings: General and Peers >> Info card

"The ordering could be for example Addresses, Account-chain Stats, Security, Node Management, Display (vertically expanded), and then Wallet Options and Backup as small cards" --Vilkris

**Comment by KingGorrin** [comment]
This issue was migrated to https://github.com/zenon-network/syrius/issues/80
