### ISSUE TITLE
Unable to register pillar with Syrius

### ISSUE THREAD

**Issue by sol-znn** [hypercore-one/syrius#2]
**Describe the bug**
Users are unable to register a pillar using Syrius v0.0.6.
After depositing QSR, they reach the `ZNN management` step but the `Next` button does not allow them to proceed.

**To Reproduce**
Precondition 1: your account must have enough ZNN and QSR to meet the Pillar Registration deposit requirements.
Precondition 2: your account must have enough fused QSR to pass the initial Plasma check

1. Launch Syrius v0.0.6
2. Navigate to the Pillars
3. Click on the `Spawn` button in the `Create Pillar` widget
4. Plasma check > click Next
5. Pillar type > click Continue
6. QSR management > click Deposit > wait for the transaction to complete > click Next
7. ZNN management > click Next

**Expected behavior**
Users should be able to complete the Pillar Registration process

**Screenshots**
Example of symptoms
- QSR management circle is greyed out despite having passed QSR deposit validation
- ZNN management `Next` button does nothing despite having the required amount
<img src="https://user-images.githubusercontent.com/104875699/236091103-c1d53e46-aeea-4169-b063-6874e7d8dd07.png" width=40% height=40%>

**Desktop**
 - Syrius version: v0.0.6
 - OS: any
 - Commit hash: c996cc404f721b329d12e9a638a149acd6648bf3

**Comment by sol-znn** [comment]
The issue was introduced in [this commit](https://github.com/zenon-network/syrius/commit/437a34ee663973feb6fbdf8608870263b335d1d1#diff-c7582346efa24e5560b757eb5e3601dff5ffbb1b7a587399801f9379c5710665R1032) and can be resolved if we call the `_saveProgressAndNavigateToNextStep` function.

Fix
https://github.com/hypercore-one/syrius/commit/91f00b4d8d389f8ecc6b3023c0b61e39490de1de

Tests
- Registered pillar on Testnet
- Deposited and withdrew QSR
- Attempted to register pillar with existing name and producer addresses (did not succeed)

Expected result
<img src="https://user-images.githubusercontent.com/104875699/236092781-94260b0a-fbc8-48bf-994a-b3cf18b4ce35.png" width=40% height=40%>

**Comment by KingGorrin** [comment]
I've reviewed https://github.com/zenon-network/syrius/pull/19 and mentioned that the `setState` is already called in the `_saveProgressAndNavigateToNextStep` method and can be removed. However, both methods work.
