### ISSUE TITLE
UI/UX - AZ Donations require a ZNN balance

### ISSUE THREAD

**Issue by sol-znn** [hypercore-one/syrius#26]
**Is your feature request related to a problem? Please describe.**
Path: Syrius > AZ tab > Donate
Users require a ZNN balance to be able to donate funds to the mothership.
This doesn't consider addresses with 0 ZNN / >0 QSR

**Describe the solution you'd like**
We can change the requirement to an OR operator:
`account has >0 ZNN or >0 QSR`
File: https://github.com/hypercore-one/syrius/blob/develop/lib/widgets/modular_widgets/accelerator_widgets/accelerator_donation_stepper.dart

**Comment by KingGorrin** [comment]
This issue was migrated to https://github.com/zenon-network/syrius/issues/79
