### ISSUE TITLE
UI/UX: Pillar type selection is unnecessary when spawning a Pillar

### ISSUE THREAD

**Issue by vilkris4** [hypercore-one/syrius#3]
**Describe the bug**
When spawning a Pillar the user is presented with a Pillar type selection step. Only one Pillar type can be selected, making it an unnecessary step for the user.

**To Reproduce**
Precondition 1: your account must have enough fused QSR to pass the initial Plasma check

1. Launch Syrius v0.0.6
2. Navigate to the Pillars tab
3. Click on the Spawn button in the Create Pillar widget
4. Plasma check > click Next

**Expected behavior**
The next step should be QSR management.

**Actual behaviour**
The next step is Pillar type selection.

**Screenshots**
<img src="https://user-images.githubusercontent.com/90819192/236127322-dc612b36-3c16-4d8c-bd3f-80acb5d031ee.png" height="400">

**Additional details**
In the v0.0.6 update the legacy Pillar registration feature was removed which makes the Pillar type selection unnecessary since only the "regular Pillar" type can now be selected.

**Desktop**
* Syrius version: v0.0.6
* OS: any
* Commit hash: https://github.com/hypercore-one/syrius/commit/c996cc404f721b329d12e9a638a149acd6648bf3

**Comment by georgezgeorgez** [comment]
Not sure if I would consider this a bug
Maybe need a category for "nice to have"
Definitely want to have good UX/UI and I understand the need for satisfying personal aesthetics
so if it's easy to change go for it

but the pillar registration flow isn't something that is used too often so i wouldn't consider this a priority in any case

**Comment by sol-znn** [comment]
should we have an `improvement` [category](https://mm.0x3639.com/boards/workspace/bjqwiwqxqtnb8xf1mab1fnu8ua/bdw6atoqxgirqjcuuz5ckxu3naa/vqsgy3jdce7f3bcqapjnstz86xh)?

**Comment by vilkris4** [comment]
I'm fine with labeling it as something else, like `improvement` if it makes more sense to others. UI/UX issues aren't always functional bugs but in my opinion they're still bugs, since it's an end-user facing application. UI/UX shouldn't really be about personal preference but primarily based on generally accepted guidelines for good usability, such as [these](https://www.nngroup.com/articles/ten-usability-heuristics/).

This isn't high priority but it is a quick thing to fix.
