### ISSUE TITLE
Node connection established when canceling the Chain identifier mismatch dialog

### ISSUE THREAD

**Issue by vilkris4** [hypercore-one/syrius#5]
**Describe the bug**
When connecting to a node that has a different chain ID than the one that is set for Syrius, a `Chain identifier mismatch` dialog is shown prompting the user to either `Cancel` or `Proceed anyway`. When pressing `Cancel` the connection to the new node is still established. The `Node Management` list then shows that Syrius is still connected to the previously selected node when it's not.

**To Reproduce**
Precondition 1: you need access to two different nodes that are not the Embedded Node.

1. Navigate to Settings > Node Management
2. Make sure you're connected to a node that is not the Embedded Node
3. Open Client chain identifier selection and set the identifier to a random number, like 999 for example.
4. In Node selection connect to another node that is not the Embedded Node
5. You should see the Chain identifier mismatch popup. Press Cancel.

**Expected behavior**
The connection to the node is not established.

**Actual behavior**
The connection to the node is established. On the UI this can be seen by the momentum height card updating.

**Desktop**
* Syrius version: v0.0.6
* OS: any
* Commit hash: https://github.com/hypercore-one/syrius/commit/c996cc404f721b329d12e9a638a149acd6648bf3

**Comment by sol-znn** [comment]
Additional info: the client switches to the target node but doesn't save the selection to hive.
Upon restarting Syrius, the wallet returns to the previous node.

**Comment by KingGorrin** [comment]
This issue was migrated to https://github.com/zenon-network/syrius/issues/81
