### ISSUE TITLE
Syrius crashes on W11

### ISSUE THREAD

**Issue by oxmah** [hypercore-one/syrius#52]
Syrius crashes everytime I launch it. I installed it on Windows 11, tried both the 0.0.7 and 0.0.10rc2 and both crash when I launch it. I tried every single body position, form and technic. First I opted for the baseball style, arm way behind my back, full extension, big stretch, then rotation and full power. I then tried to launch it like those athlete's launching iron balls. They're super strong you know? Every single time Syrius pathetically crashes on the ground and I lose one laptop. I lost a fuckton of laptop trying to launch Syriois. I can't take it anymore. Can the devs do something?

**Comment by sol-znn** [comment]
Is this serious? Please provide a log.
